apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: swe645-hw2-luis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-hw2-luis
  template:
    metadata:
      labels:
        app: swe645-hw2-luis
    spec:
      containers:
      - name: swe645-hw2-luis
        image: luissncs/swe645-hw2-luis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
