apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: swe645-hw2-luis
spec:
  selector:
    matchLabels:
      app: swe645-hw2-luis
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: swe645-hw2-luis
    spec:
      containers:
      - name: swe645-hw2-luis
        image: luissncs/swe645-hw:swe645-hw2-luis_1
        ports:
        - containerPort: 8080
