apiVersion: v1
kind: Service
metadata:
  name: swe645-hw2-luis-service
spec:
  type: LoadBalancer
  selector:
    app: swe645-hw2-luis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
